### ISSUE TITLE
Installation Tutorial?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [elasticinbox/elasticinbox-java#28]
Hello, 

This is a really nice project and I really need something like that. Did make any tutorials on how to install ElasticInbox? I'm interested in creating an scalable email receiving platform on AWS. My application processes thousands of e-mail attachments per hour and this is our bottleneck. 

We are currently migrating from a dedicated server to AWS. We have almost everything migrated already, except our mail receiving service, which is still in the old dedicated servers.

Can you point me to the right direction?

Thank you very much!

**Comment by rstml** [comment]
Hi Daniel,

You are right, that's one of the things which are missing. Here are few tips:

First of all you will need to install Cassandra. This is the only metadata store we support at the moment. There are plenty of tutorials how to install it on AWS. Theoretically, AWS DynamoDB is very similar to Cassandra and it should be trivial to write driver for it.

Once you've got Cassandra, then create schema: https://github.com/elasticinbox/elasticinbox/blob/master/config/elasticinbox.cml

Next download latest release package and configure https://github.com/elasticinbox/elasticinbox/blob/master/config/elasticinbox.yaml. Yaml file has all necessary comments and self-explanatory.

Finally, run bin/elasticinbox. That's it!

Let me know if anything isn't clear.

PS: Note that POP3 and IMAP support isn't there yet. So it's mostly suitable for pure webmails at the moment. We are working on adding those.

## 

Rustam.

**Comment by rstml** [comment]
Getting started guide is now available at http://www.elasticinbox.com/getting-started/
