### ISSUE TITLE
Enable label ordering

### ISSUE THREAD

**Issue by Danita** [elasticinbox/elasticinbox-java#37]
It seems there is no way to get the labels in the order the user created them, or in any predictable order whatsoever :-P (except reserved labels). This could be a UI headache, because when the user switches between several hypotetical clients the label ordering won't be preserved among them unless we add another server layer between the client and EI to store the order.

Is this the intended effect?

This is an sample response to illustrate my point:

`GET /mailbox/?metadata=true`

``` javascript
{
    "1100": {
        "unread": 0,
        "total": 0,
        "name": "myNewLabel^myNewNestedLabel"
    },
    "0": {
        "total": 14,
        "unread": 14,
        "size": 2364721,
        "name": "all"
    },
    "1": {
        "unread": 14,
        "total": 14,
        "name": "inbox"
    },
    "2": {
        "unread": 0,
        "total": 0,
        "name": "drafts"
    },
    "3": {
        "unread": 0,
        "total": 0,
        "name": "sent"
    },
    "4": {
        "unread": 0,
        "total": 0,
        "name": "trash"
    },
    "5": {
        "unread": 0,
        "total": 0,
        "name": "spam"
    },
    "6": {
        "unread": 0,
        "total": 0,
        "name": "starred"
    },
    "7": {
        "unread": 0,
        "total": 0,
        "name": "important"
    },
    "8": {
        "unread": 0,
        "total": 0,
        "name": "notifications"
    },
    "9": {
        "unread": 0,
        "total": 0,
        "name": "attachments"
    },
    "10": {
        "unread": 14,
        "total": 14,
        "name": "pop3"
    },
    "1958": {
        "unread": 0,
        "total": 0,
        "name": "myNewLabel"
    }
}
```

**Comment by rstml** [comment]
Label ID is a random number. You should not rely on this for ordering.

We were planning to add custom label attributes which client can set/get. Consider following:

``` javascript
    ...
    "1100": {
        "unread": 0,
        "total": 0,
        "name": "myNewLabel^myNewNestedLabel",
        "x-order" : "2",
        "x-color" : "blue",
        "x-visible" : "false"
    },
    "1958": {
        "unread": 0,
        "total": 0,
        "name": "myNewLabel",
        "x-order" : "3",
        "x-color" : "red"
        "x-visible" : "true"
    }
    ...
```

Using custom `x-` (only for example, could be something else) attributes you can store any information associated with a label - order, color, etc. One scenario is that client may want to reorder labels.

ElasticInbox won't know anything about those fields however. You will need to order them manually in your frontend app.

Would that approach work for you?

**Comment by Danita** [comment]
That sounds fantastic! I think those custom fields might be all what is needed in the frontend to store collapsed/expanded, colors and so on. I look forward to see this change, thanks.

**Comment by rstml** [comment]
Closing in favor of #39
