### ISSUE TITLE
Are there plans to support the Sieve language?

### ISSUE THREAD

**Issue by Danita** [elasticinbox/elasticinbox-java#45]
It would be nice to have support to define filtering rules for each mailbox.

Reference:
http://sieve.info/

**Comment by rstml** [comment]
Yes, we plan to implement SIEVE based filtering rules and jSieve is shortlisted for that purpose. However, there are no timelines. Some info regarding SIEVE was provided here https://groups.google.com/d/msg/elasticinbox/OLyX7VFS9Dw/wPJPksTy1ykJ

PS: please use mailing list for questions.

**Comment by Danita** [comment]
Thanks! Sorry, I didn't knew the mailing list existed :blush:
