### ISSUE TITLE
MessageId always coming out `null` on parsed message

### ISSUE THREAD

**Issue by Danita** [elasticinbox/elasticinbox-java#49]
I don't know wether this is happening since the last update, but I've been noticing that `messageId` is always returning `null` for parsed messages, even though in the corresponding raw message the header `message-id` is present and properly complete. I've tested with old and new messages in my mailbox and it's always the same. 

Any ideas? Could this be a configuration issue?

**Comment by rstml** [comment]
Could you please provide command to reproduce and sample response?

**Comment by Danita** [comment]
It happens with each and every mail received:

Example of request for parsed message:

`GET /rest/v2/domain/user/mailbox/message/ef631ab0-13fd-11e3-a800-22000a9887a0`

Sample response:

``` javascript
{
    "message": {
        "from": [{
            "name": "xxx",
            "address": "xxx@xxx.com"
        }],
        "to": [{
            "name": "xxx",
            "address": "xxx@xxx.com"
        }, {
            "name": "xxx",
            "address": "xxx@xxx.com"
        }],
        "cc": null,
        "bcc": null,
        "subject": "Search the CPAN - metacpan.org - Perl programming language",
        "date": "2013-09-02T18:31:52.000+0000",
        "messageId": null,
        "size": 7472,
        "location": "blob://db/ef631ab0-13fd-11e3-a800-22000a9887a0?c=dfl&b=1",
        "plainBody": null,
        "htmlBody": "<html>\r\n  <head>\r\n\r\n    <meta http-equiv=\"content-type\" content=\"text/html; charset=ISO-8859-1\">...",
        "labels": [0, 1, 10],
        "markers": ["SEEN"],
        "parts": {
            "2.2": {
                "contentId": "part1.05090702.08050808@xxx.com",
                "mimeType": "image/gif",
                "fileName": "logo_footer.gif",
                "disposition": "inline",
                "size": 1698
            }
        }
    }
}
```

Example of request of raw message:

`GET /rest/v2/domain/user/mailbox/message/ef631ab0-13fd-11e3-a800-22000a9887a0/raw`

Sample response:

```
Received: from mail-ye0-f173.google.com (mail-ye0-f173.google.com [209.85.213.173])
    by ip-xx-xx-xx-xxx.ec2.internal (Postfix) with ESMTPS id 627E161F0C
    for <xxx@xxx.com>; Mon,  2 Sep 2013 18:31:51 +0000 (UTC)
Received: by mail-ye0-f173.google.com with SMTP id m3so1471058yen.32
        for <xxx@xxx.com>; Mon, 02 Sep 2013 11:31:50 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:message-id:date:from:organization:user-agent
         :mime-version:to:subject:content-type;
        bh=uQWfZKPUVxseZAwZEPA5pFGpwzwnFhF2UBvBJMGuckU=;
        b=LlSdKaP2Wyg+uXOOO/p9kVL6oMDhtUqT6bp2wKLdopN4ACAQDIQAJCthVMMuYeOH1k
         xIAuYiJOXdHwc1BuxFkO+sEFean+EcBultUGncK2Ld2cau8ccsWIeHcZFDs9WIbdBsiX
         hpyJsp3VxHuneqtjU8c6MgvoSRxwBrqBd6MI+diRyFYsueSLTj2p+z6NkaAu1+tlbPsn
         ZmdZeNCo4H73gSKi3Uiwbm6S+oqGMUjnXUFQvXtN3jlW+XMmrdRMMiLtw0s2HKI60Pwr
         5ifn/FUTNTkvN7zRN+pKKiq/o+MMDhdJbGPkhBrP9BiDBYjsTiibLzc7rlYdIaT/VLVt
         I3Pg==
X-Gm-Message-State: ALoCoQkAmDkeC3YqV81xw8PNi3Lt09twgxQQIx6N55/1dQVp8kEEf/SXfjIfNHvYfMHHtl7sr56K
X-Received: by 10.236.153.169 with SMTP id f29mr1455157yhk.82.1378146710774;
        Mon, 02 Sep 2013 11:31:50 -0700 (PDT)
Received: from [10.254.40.17] ([200.0.230.234])
        by mx.google.com with ESMTPSA id g25sm17452837yhg.6.1969.12.31.16.00.00
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Mon, 02 Sep 2013 11:31:50 -0700 (PDT)
Message-ID: <5224D998.4000307@viajeros.com>
Date: Mon, 02 Sep 2013 15:31:52 -0300
From: =?ISO-8859-1?Q?Daniela_Rodr=EDguez_Careri?= <xxx@xxx.com>
Organization: xxxxxxxxxx
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:17.0) Gecko/20130801 Thunderbird/17.0.8
MIME-Version: 1.0
To: =?ISO-8859-1?Q?Daniela_Rodr=EDguez?= <xxx@xxx.com>, 
 "Dana (CloudMas)" <xxx@xxx.com>
Subject: Search the CPAN - metacpan.org - Perl programming language
Content-Type: multipart/alternative;
 boundary="------------020900010103070700050107"

... (truncated)
```

Sorry I had to replace sensitive information with `xxx` but everything else is verbatim. If you need the complete raw message please advice where I cand send it.

**Comment by rstml** [comment]
Thanks. I think the problem could be with json serializer which should by default ignore all fields with null values (so you should not see cc, bcc, messageid and plainbody in the sample response).

Basically, messageId should not be shown because you already know it forms the request. Do you really need messageId to be returned in the response?

**Comment by Danita** [comment]
> ...json serializer which should by default ignore all fields with null values (so you should not see cc, bcc, messageid and plainbody in the sample response).

I don't mind the fields coming out `null` when there is nothing on them. What I meant is if this field shouldn't be filled with the parsed data from the message `message-id` header?

> Basically, messageId should not be shown because you already know it forms the request. Do you really need messageId to be returned in the response?

I think we're mistaking `messageId` for `uuid`. I _know_ the `uuid` of the message because I requested for it. But I don't know the `messageId` the sender has assigned to it, usually in the form `<xxxxx@xxxxx.com>`. The message I quoted up there is an incoming message from a third party, not generated by my application.

The original message `messageId` is needed when my client application needs to _reply_ or _forward_ the message to another recipient so it can reference it on the `in-reply-to` and `references` headers.

Otherwise I wouldn't know how to implement that feature other than _hand-parsing_ the raw message...

**Comment by rstml** [comment]
Ah, I see now. `messageId` is the internal one, i.e. uuid. As I said, it should be hidden and used for internal purposes only.

`message-id`, `in-reply-to` and `references` email fields are not extracted to the metadata currently although it is on the list. They are part of message threading support task. I'll see if we can fast-track `message-id`. Agree that it's vital for replies.

**Comment by Danita** [comment]
Oh, so I've misunderstood the meaning of `messageId`... :blush: 

Well, I'm glad to hear `message-id` header extracted to metadata is on the way. It would be great to have the other headers too, but I guess I'll have to wait until threading support is complete, isn't it :smile: 

Thanks a lot!
