### ISSUE TITLE
Get message bodies along with metadata

### ISSUE THREAD

**Issue by Danita** [elasticinbox/elasticinbox-java#50]
As discussed in the mailing list (https://groups.google.com/forum/#!topic/elasticinbox/LW6DGE157HA) it might be necessary to provide a method to retrieve message bodies along with their metadata when requesting a message listing.

Rationale: We've discovered a common use case when developing a client for ElasticInbox where we need to show a small excerpt of each message listed on the mailbox. In such instance currently are needed `1 + n` requests, where `n` is the number of messages displayed per page. The first request is for retrieving the list, the remaining `n` requests are for retrieving each and every message body. This is inefficient. If ElasticInbox could be configured to return the bodies along with the metadata the requests could be cut to just 1.

Proposal:
- Add a `includebodies=true` parameter to the listing url.
- `includebodies` will not have effect if `metadata=true` is not present.
- It could be beneficial to configure ElasticInbox to truncate the bodies to a specified length. Note that this could result in invalid HTML output due to missing closing tags.

Example request:

http://mail.example.com/rest/v2/example.com/danita/mailbox/label/1?metadata=true&includebodies=true

Example response:

```
{
    944e8900-6382-11e3-852b-22000a9887a0: {
        from: [
            { name: "Example.com", address: "in...@example.com" }
        ],
        to: [
            { name: "Danita", address: "dan...@example.com" },

        ],
        cc: null,
        bcc: null,
        subject: "Newsletter #661",
        date: "2013-12-12T18:46:15.000+0000",
        messageId: null,
        size: 22336,
        location: "blob://db/944e8900-6382-11e3-852b-22000a9887a0?c=dfl&b=1",
        plainBody: "Newsletter #661: Principles of interaction design...",
        htmlBody: "<html><head></head><body><h1>Newsletter #661: Principles of interaction design</h1><p>...</p></body></html>",
        labels: [ 0, 1, 10 ],
        markers: [ "SEEN" ],
        parts: null
    },
    ...
}
```

**Comment by rstml** [comment]
This is now done. You can use `...&includebody=true` to get bodies. Will update docs soon.

I wanted to add body trimming for large messages. Gmail and Yahoo both does it. But your comment about HTML is valid and I wonder how they handle this.

**Comment by temilmg** [comment]
Dont know if its a sane idea or not but.... If only an except is needed maybe it would be all right to strip out all html tags and take say the first 200 characters (maybe putting ellipsis at the end). 

Jsoup or regular expressions could be used. 

Document doc = Jsoup.parse(emailContent);
String parsedContent = doc.text();
String emailExcerpt = parsedContent.substring(0,200) + " ...";

if html tags are needed i think Jsoup can be used as well! 

Dont know how all of this is performance wise!

**Comment by Danita** [comment]
Here's what we are currently doing in our application, which gives an output that is almost character by character equal to Gmail: https://gist.github.com/Danita/776cb5747c053616940d

**Comment by rstml** [comment]
DOM parsing is a bit expensive. I was thinking about more lightweight approach such as detecting and closing open tags in a single pass.

I updated docs and will close this ticket. If you find that full message content is causing problems, feel free to open a new ticket to trim content.

Btw, from my experiments it looks like Gmail returns only first 100K or so.

**Comment by Danita** [comment]
Are there any plans to release this? I can't find it on the latest release.

**Comment by rstml** [comment]
It is in master which you can build yourself. Didn't want to release 0.5 with minor features.
